# Change these first
owner: sudoswap # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sudo Frontend
    url: https://sudoswap.xyz
  - name: Sudo Backend
    url: https://sudoapi.xyz/v1/health
  - name: Cache
    url: http://35.89.131.209:6379
  - name: Indexer
    url: http://127.0.0.1:6000/nfts/get?address=0xd8da6bf26964af9d7eed9e03e53415d37aa96045

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sudoswap Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
