# Change these first
owner: sudoswap # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sudo Website
    url: https://sudoswap.xyz
  - name: Sudo Website V1
    url: https://v1.sudoswap.xyz
  - name: Edge API
    url: https://edge.sudoapi.xyz/api/health
  - name: Sudo API V2
    url: https://v2.sudoapi.xyz/sudo/app/status
    headers:
      - "X-Sudo-Dev: $V2_API_DEV_TOKEN"
  - name: Sudo API (/health)
    url: https://sudoapi.xyz/v1/health
  - name: Mainnet Indexer (test query)
    url: https://ecstatic-armor-380509.uw.r.appspot.com/status
  - name: Mainnet Ethereum Node (rpc)
    method: POST
    url: https://eth-mainnet.g.alchemy.com/v2/$ALCHEMY_API_KEY
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sudoswap.xyz
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/sudoswap/upptime/master/assets/logo_square.svg
  themeUrl: https://raw.githubusercontent.com/sudoswap/upptime/master/assets/theme.css
  name: sudoswap upptime
  introTitle: "sudoswap.xyz status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
