# Change these first
owner: sudoswap # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sudo Website
    url: https://sudoswap.xyz
  - name: Sudo Website V1
    url: https://v1.sudoswap.xyz
  - name: Edge API
    url: https://edge.sudoapi.xyz/api/health
  - name: Sudo API V2
    url: https://v2.sudoapi.xyz/app/status
    headers:
      - "X-Sudo-Dev: $V2_API_DEV_TOKEN"
  - name: Sudo API (/health)
    url: https://sudoapi.xyz/v1/health
  - name: Mainnet Indexer (test query)
    url: https://ecstatic-armor-380509.uw.r.appspot.com/status
  - name: Mainnet Ethereum Node (rpc)
    method: POST
    url: https://eth-mainnet.g.alchemy.com/v2/$ALCHEMY_API_KEY
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}'
  - name: Defined.fi
    method: POST
    url: https://graph.codex.io/graphql
    headers:
      - "Authorization:$DEFINED_API_KEY"
      - "Content-Type: application/json"
    body: '{ "query": "{ getNetworks { name, id } }"}'

status-website:
  cname: status.sudoswap.xyz
  logoUrl: https://status.sudoswap.xyz/logo_square.svg
  themeUrl: https://status.sudoswap.xyz/theme.css
  name: sudoswap upptime
  introTitle: "sudoswap.xyz status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
